import { FormEvent, useEffect, useMemo, useState } from "react";

type Role="director"|"teacher"|"student";
type User={id:string;name:string;username:string;email:string;passwordHash:string;role:Role;className:string;active:boolean;createdAt:string};
type School={name:string;city:string;director:string};
type ClassRoom={id:string;name:string;year:string};
type Subject={id:string;name:string;teacherId:string};
type Task={id:string;title:string;subject:string;description:string;dueDate:string;teacherId:string;className:string};
type Exam={id:string;title:string;subject:string;date:string;teacherId:string;className:string;maxScore:number};
type Grade={id:string;examId:string;studentId:string;score:number;teacherId:string};
type Event={id:string;title:string;date:string;description:string};
type Attendance={id:string;studentId:string;date:string;present:boolean;teacherId:string};
type Mail={id:string;fromId:string;toId:string;subject:string;body:string;date:string;read:boolean};

const K={users:"school.users.v2",school:"school.data.v2",classes:"school.classes.v1",subjects:"school.subjects.v1",tasks:"school.tasks.v1",exams:"school.exams.v1",grades:"school.grades.v1",events:"school.events.v1",attendance:"school.attendance.v1",mails:"school.mails.v1",session:"school.session.v2"};
const read=<T,>(k:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(k)||"null")??f}catch{return f}};const write=(k:string,v:unknown)=>localStorage.setItem(k,JSON.stringify(v));const norm=(v:string)=>v.trim().toLowerCase();
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}

export default function App(){
 const [users,setUsers]=useState<User[]>(()=>read(K.users,[])),[school,setSchool]=useState<School>(()=>read(K.school,{name:"Minha Escola",city:"",director:""})),[classes,setClasses]=useState<ClassRoom[]>(()=>read(K.classes,[])),[subjects,setSubjects]=useState<Subject[]>(()=>read(K.subjects,[])),[tasks,setTasks]=useState<Task[]>(()=>read(K.tasks,[])),[exams,setExams]=useState<Exam[]>(()=>read(K.exams,[])),[grades,setGrades]=useState<Grade[]>(()=>read(K.grades,[])),[events,setEvents]=useState<Event[]>(()=>read(K.events,[])),[attendance,setAttendance]=useState<Attendance[]>(()=>read(K.attendance,[])),[mails,setMails]=useState<Mail[]>(()=>read(K.mails,[]));
 const [session,setSession]=useState<string|null>(()=>localStorage.getItem(K.session)),[login,setLogin]=useState({username:"",password:""}),[loginMsg,setLoginMsg]=useState(""),[view,setView]=useState("dashboard"),[msg,setMsg]=useState("");
 const [schoolForm,setSchoolForm]=useState(school),[userForm,setUserForm]=useState({name:"",username:"",email:"",password:"",role:"student" as Role,className:""}),[classForm,setClassForm]=useState({name:"",year:""}),[subjectForm,setSubjectForm]=useState({name:"",teacherId:""}),[taskForm,setTaskForm]=useState({title:"",subject:"",description:"",dueDate:"",className:""}),[examForm,setExamForm]=useState({title:"",subject:"",date:"",className:"",maxScore:"10"}),[gradeForm,setGradeForm]=useState({examId:"",studentId:"",score:""}),[eventForm,setEventForm]=useState({title:"",date:"",description:""}),[mailForm,setMailForm]=useState({toId:"",subject:"",body:""}),[attendanceDate,setAttendanceDate]=useState(new Date().toISOString().slice(0,10)),[attendanceClass,setAttendanceClass]=useState("");
 const current=users.find(u=>u.id===session),isDirector=current?.role==="director",isTeacher=current?.role==="teacher",isStudent=current?.role==="student";
 useEffect(()=>{if(!users.some(u=>u.role==="director"))void(async()=>{const u:User={id:crypto.randomUUID(),name:"Diretor da Escola",username:"diretor",email:"diretor@escola.local",passwordHash:await hash("diretor123"),role:"director",className:"",active:true,createdAt:new Date().toISOString()};const n=[...users,u];setUsers(n);write(K.users,n)})();},[]);
 useEffect(()=>{if(isDirector&&school.director!==current?.name){const s={...school,director:current!.name};setSchool(s);setSchoolForm(s);write(K.school,s)}},[isDirector,current?.name]);
 const students=users.filter(u=>u.role==="student"),teachers=users.filter(u=>u.role==="teacher"),myTasks=tasks.filter(t=>isTeacher?t.teacherId===current?.id:t.className===current?.className),myExams=exams.filter(x=>isTeacher?x.teacherId===current?.id:x.className===current?.className),inbox=mails.filter(m=>m.toId===current?.id),outbox=mails.filter(m=>m.fromId===current?.id),unread=inbox.filter(m=>!m.read).length;
 const avg=grades.filter(g=>g.studentId===current?.id).length?grades.filter(g=>g.studentId===current?.id).reduce((a,g)=>a+g.score,0)/grades.filter(g=>g.studentId===current?.id).length:0;
 async function doLogin(e:FormEvent){e.preventDefault();const p=await hash(login.password),u=users.find(x=>norm(x.username)===norm(login.username)&&x.passwordHash===p);if(!u)return setLoginMsg("Usuário ou senha incorretos.");if(!u.active)return setLoginMsg("Esta conta está bloqueada.");localStorage.setItem(K.session,u.id);setSession(u.id);setView("dashboard");}
 function logout(){localStorage.removeItem(K.session);setSession(null)}
 function feedback(s:string){setMsg(s);setTimeout(()=>setMsg(""),2500)}
 function saveSchool(e:FormEvent){e.preventDefault();const s={...schoolForm,director:current?.name||""};setSchool(s);write(K.school,s);feedback("Dados da escola salvos.")}
 async function createUser(e:FormEvent){e.preventDefault();if(!userForm.name||!userForm.username||!userForm.password)return feedback("Preencha os campos obrigatórios.");if(users.some(u=>norm(u.username)===norm(userForm.username)))return feedback("Usuário já existe.");const u:User={id:crypto.randomUUID(),name:userForm.name.trim(),username:userForm.username.trim(),email:norm(userForm.email),passwordHash:await hash(userForm.password),role:userForm.role,className:userForm.className.trim(),active:true,createdAt:new Date().toISOString()};const n=[...users,u];setUsers(n);write(K.users,n);setUserForm({name:"",username:"",email:"",password:"",role:"student",className:""});feedback("Conta criada.")}
 function createClass(e:FormEvent){e.preventDefault();const n=[...classes,{id:crypto.randomUUID(),...classForm}];setClasses(n);write(K.classes,n);setClassForm({name:"",year:""});feedback("Turma criada.")}
 function createSubject(e:FormEvent){e.preventDefault();const n=[...subjects,{id:crypto.randomUUID(),name:subjectForm.name,teacherId:subjectForm.teacherId}];setSubjects(n);write(K.subjects,n);setSubjectForm({name:"",teacherId:""});feedback("Disciplina cadastrada.")}
 function addTask(e:FormEvent){e.preventDefault();const n=[...tasks,{id:crypto.randomUUID(),...taskForm,teacherId:current!.id}];setTasks(n);write(K.tasks,n);setTaskForm({title:"",subject:"",description:"",dueDate:"",className:""});feedback("Tarefa publicada.")}
 function addExam(e:FormEvent){e.preventDefault();const n=[...exams,{id:crypto.randomUUID(),...examForm,maxScore:Number(examForm.maxScore)||10,teacherId:current!.id}];setExams(n);write(K.exams,n);setExamForm({title:"",subject:"",date:"",className:"",maxScore:"10"});feedback("Prova cadastrada.")}
 function addGrade(e:FormEvent){e.preventDefault();const ex=exams.find(x=>x.id===gradeForm.examId);const score=Number(gradeForm.score);if(!ex||score<0||score>ex.maxScore)return feedback("Confira a prova e a nota.");const g={id:crypto.randomUUID(),examId:ex.id,studentId:gradeForm.studentId,score,teacherId:current!.id};const n=[...grades.filter(x=>!(x.examId===g.examId&&x.studentId===g.studentId)),g];setGrades(n);write(K.grades,n);feedback("Nota lançada.")}
 function addEvent(e:FormEvent){e.preventDefault();const n=[...events,{id:crypto.randomUUID(),...eventForm}];setEvents(n);write(K.events,n);setEventForm({title:"",date:"",description:""});feedback("Evento adicionado ao calendário.")}
 function addMail(e:FormEvent){e.preventDefault();if(!mailForm.toId)return feedback("Selecione um destinatário.");const n=[...mails,{id:crypto.randomUUID(),fromId:current!.id,toId:mailForm.toId,subject:mailForm.subject,body:mailForm.body,date:new Date().toISOString(),read:false}];setMails(n);write(K.mails,n);setMailForm({toId:"",subject:"",body:""});feedback("E-mail enviado.")}
 function markRead(id:string){const n=mails.map(m=>m.id===id?{...m,read:true}:m);setMails(n);write(K.mails,n)}
 function markAttendance(studentId:string,present:boolean){const n=[...attendance.filter(a=>!(a.studentId===studentId&&a.date===attendanceDate)),{id:crypto.randomUUID(),studentId,date:attendanceDate,present,teacherId:current!.id}];setAttendance(n);write(K.attendance,n)}
 function toggleUser(id:string){const n=users.map(u=>u.id===id?{...u,active:!u.active}:u);setUsers(n);write(K.users,n)}
 function removeUser(id:string){if(id===current?.id)return;const n=users.filter(u=>u.id!==id);setUsers(n);write(K.users,n)}
 if(!current)return <main className="authPage"><section className="authCard"><span className="badge">PLATAFORMA ESCOLAR</span><h1>Entrar</h1><p className="muted">Diretor, professores e alunos em um só lugar.</p><form onSubmit={doLogin}><label>Usuário<input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} required/></label><label>Senha<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required/></label>{loginMsg&&<p className="message">{loginMsg}</p>}<button>Entrar</button></form><div className="demoBox"><b>Diretor de demonstração</b><span>Usuário: <strong>diretor</strong> · Senha: <strong>diretor123</strong></span></div></section></main>;
 const role=isDirector?"Diretor":isTeacher?"Professor":"Aluno";
 const nav=(v:string,label:string)=><button className={view===v?"navActive":""} onClick={()=>setView(v)}>{label}</button>;
 return <div className="appShell"><aside className="sidebar"><div><span className="badge">PLATAFORMA ESCOLAR</span><h2>{school.name}</h2><nav>{nav("dashboard","📊 Dashboard")}{nav("calendar","📅 Calendário")}{nav("mail","✉️ E-mails")} {isDirector&&<>{nav("school","🏫 Escola")}{nav("people","👥 Usuários")}{nav("classes","🏷️ Turmas")}{nav("subjects","📚 Disciplinas")}</>}{isTeacher&&<>{nav("tasks","📝 Tarefas")}{nav("exams","📋 Provas")}{nav("grades","🎓 Notas")}{nav("attendance","✓ Frequência")}</>}{isStudent&&<>{nav("tasks","📝 Tarefas")}{nav("exams","📋 Provas")}{nav("grades","📖 Boletim")}</>}{nav("profile","👤 Perfil")}</nav></div><div className="accountBox"><strong>{current.name}</strong><span>@{current.username}</span><span className="role">{role}</span><button className="logout" onClick={logout}>Sair</button></div></aside>
 <main className="content">
 {msg&&<div className="toast">{msg}</div>}
 {view==="dashboard"&&<><div className="pageTitle"><span className="badge">{role.toUpperCase()}</span><h1>Olá, {current.name}!</h1><p className="muted">{school.name}{school.city&&" · "+school.city}</p></div><div className="stats"><div className="statCard"><span>Perfil</span><b>{role}</b></div><div className="statCard"><span>{isStudent?"Média":isTeacher?"Tarefas":"Usuários"}</span><b>{isStudent?avg.toFixed(1):isTeacher?myTasks.length:users.length}</b></div><div className="statCard"><span>E-mails não lidos</span><b>{unread}</b></div></div><section className="card"><h2>Acesso rápido</h2><div className="quick">{isDirector&&<><button onClick={()=>setView("people")}>Cadastrar pessoas</button><button onClick={()=>setView("classes")}>Gerenciar turmas</button></>}{isTeacher&&<><button onClick={()=>setView("tasks")}>Nova tarefa</button><button onClick={()=>setView("grades")}>Lançar nota</button></>}{isStudent&&<><button onClick={()=>setView("grades")}>Ver boletim</button><button onClick={()=>setView("calendar")}>Ver calendário</button></>}</div></section></>}
 {view==="school"&&isDirector&&<section className="card"><span className="badge">ESCOLA</span><h1>Cadastro da escola</h1><form onSubmit={saveSchool} className="grid"><label>Nome da escola<input value={schoolForm.name} onChange={e=>setSchoolForm({...schoolForm,name:e.target.value})} required/></label><label>Cidade<input value={schoolForm.city} onChange={e=>setSchoolForm({...schoolForm,city:e.target.value})}/></label><button>Salvar</button></form></section>}
 {view==="people"&&isDirector&&<><section className="card"><span className="badge">CONTAS</span><h1>Alunos e professores</h1><form onSubmit={createUser}><div className="grid"><label>Nome<input value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})} required/></label><label>Usuário<input value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})} required/></label><label>E-mail<input type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Senha<input type="password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} required/></label><label>Tipo<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value as Role})}><option value="student">Aluno</option><option value="teacher">Professor</option><option value="director">Diretor</option></select></label><label>Turma<input value={userForm.className} onChange={e=>setUserForm({...userForm,className:e.target.value})} placeholder="Ex.: 8º A"/></label></div><button>Criar conta</button></form></section><section className="card"><h2>Usuários ({users.length})</h2><div className="users">{users.map(u=><div className="user" key={u.id}><div><b>{u.name}</b><span>{u.username} · {u.role} {u.className&&"· "+u.className}</span></div>{u.id!==current.id&&<div className="actions"><button className="secondary" onClick={()=>toggleUser(u.id)}>{u.active?"Bloquear":"Desbloquear"}</button><button className="remove" onClick={()=>removeUser(u.id)}>Excluir</button></div>}</div>)}</div></section></>}
 {view==="classes"&&isDirector&&<><section className="card"><span className="badge">TURMAS</span><h1>Gerenciar turmas</h1><form onSubmit={createClass} className="grid"><label>Nome da turma<input placeholder="Ex.: 8º A" value={classForm.name} onChange={e=>setClassForm({...classForm,name:e.target.value})} required/></label><label>Ano letivo<input value={classForm.year} onChange={e=>setClassForm({...classForm,year:e.target.value})} placeholder="2026"/></label><button>Criar turma</button></form></section><section className="card"><h2>Turmas cadastradas</h2>{classes.map(c=><div className="item" key={c.id}><b>{c.name}</b><span>Ano letivo: {c.year||"não informado"} · {students.filter(s=>s.className===c.name).length} alunos</span></div>)}</section></>}
 {view==="subjects"&&isDirector&&<><section className="card"><span className="badge">DISCIPLINAS</span><h1>Gerenciar disciplinas</h1><form onSubmit={createSubject} className="grid"><label>Disciplina<input value={subjectForm.name} onChange={e=>setSubjectForm({...subjectForm,name:e.target.value})} placeholder="Matemática" required/></label><label>Professor<select value={subjectForm.teacherId} onChange={e=>setSubjectForm({...subjectForm,teacherId:e.target.value})}><option value="">Selecione</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button>Cadastrar disciplina</button></form></section><section className="card"><h2>Disciplinas</h2>{subjects.map(s=><div className="item" key={s.id}><b>{s.name}</b><span>Professor: {users.find(u=>u.id===s.teacherId)?.name||"Não definido"}</span></div>)}</section></>}
 {view==="tasks"&&<section className="card"><span className="badge">TAREFAS</span><h1>{isTeacher?"Minhas tarefas":"Tarefas da minha turma"}</h1>{isTeacher&&<form onSubmit={addTask}><div className="grid"><label>Título<input value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})} required/></label><label>Disciplina<input value={taskForm.subject} onChange={e=>setTaskForm({...taskForm,subject:e.target.value})} required/></label><label>Turma<input value={taskForm.className} onChange={e=>setTaskForm({...taskForm,className:e.target.value})} required/></label><label>Prazo<input type="date" value={taskForm.dueDate} onChange={e=>setTaskForm({...taskForm,dueDate:e.target.value})}/></label><label className="full">Descrição<textarea value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/></label></div><button>Publicar tarefa</button></form>}{myTasks.map(t=><div className="item" key={t.id}><b>{t.title}</b><span>{t.subject} · {t.className} · prazo {t.dueDate||"não definido"}</span><p>{t.description}</p></div>)}{!myTasks.length&&<p className="muted">Nenhuma tarefa encontrada.</p>}</section>}
 {view==="exams"&&<section className="card"><span className="badge">PROVAS</span><h1>{isTeacher?"Minhas provas":"Provas da minha turma"}</h1>{isTeacher&&<form onSubmit={addExam}><div className="grid"><label>Título<input value={examForm.title} onChange={e=>setExamForm({...examForm,title:e.target.value})} required/></label><label>Disciplina<input value={examForm.subject} onChange={e=>setExamForm({...examForm,subject:e.target.value})} required/></label><label>Data<input type="date" value={examForm.date} onChange={e=>setExamForm({...examForm,date:e.target.value})} required/></label><label>Turma<input value={examForm.className} onChange={e=>setExamForm({...examForm,className:e.target.value})} required/></label><label>Valor máximo<input type="number" min="1" value={examForm.maxScore} onChange={e=>setExamForm({...examForm,maxScore:e.target.value})}/></label></div><button>Cadastrar prova</button></form>}{myExams.map(x=><div className="item" key={x.id}><b>{x.title}</b><span>{x.subject} · {x.className} · {x.date} · máximo {x.maxScore}</span></div>)}{!myExams.length&&<p className="muted">Nenhuma prova encontrada.</p>}</section>}
 {view==="grades"&&isTeacher&&<><section className="card"><span className="badge">NOTAS</span><h1>Lançar nota</h1><form onSubmit={addGrade} className="grid"><label>Prova<select value={gradeForm.examId} onChange={e=>setGradeForm({...gradeForm,examId:e.target.value})} required><option value="">Selecione</option>{myExams.map(x=><option key={x.id} value={x.id}>{x.title} · {x.className}</option>)}</select></label><label>Aluno<select value={gradeForm.studentId} onChange={e=>setGradeForm({...gradeForm,studentId:e.target.value})} required><option value="">Selecione</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.className}</option>)}</select></label><label>Nota<input type="number" step=".1" min="0" value={gradeForm.score} onChange={e=>setGradeForm({...gradeForm,score:e.target.value})} required/></label><button>Lançar nota</button></form></section><section className="card"><h2>Notas lançadas</h2>{grades.filter(g=>g.teacherId===current.id).map(g=>{const e=exams.find(x=>x.id===g.examId),s=users.find(x=>x.id===g.studentId);return <div className="item" key={g.id}><b>{s?.name}</b><span>{e?.subject} · {e?.title} · {g.score}/{e?.maxScore}</span></div>})}</section></>}
 {view==="grades"&&isStudent&&<section className="card"><span className="badge">BOLETIM ESCOLAR</span><h1>Meu boletim</h1><div className="stats"><div className="statCard"><span>Média geral</span><b>{avg.toFixed(1)}</b></div><div className="statCard"><span>Avaliações</span><b>{grades.filter(g=>g.studentId===current.id).length}</b></div><div className="statCard"><span>Turma</span><b>{current.className||"Não definida"}</b></div></div>{grades.filter(g=>g.studentId===current.id).map(g=>{const e=exams.find(x=>x.id===g.examId);return <div className="item" key={g.id}><b>{e?.subject||"Disciplina"}</b><span>{e?.title} · {g.score}/{e?.maxScore}</span></div>})}</section>}
 {view==="attendance"&&isTeacher&&<section className="card"><span className="badge">FREQUÊNCIA</span><h1>Controle de presença</h1><div className="grid"><label>Data<input type="date" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/></label><label>Turma<select value={attendanceClass} onChange={e=>setAttendanceClass(e.target.value)}><option value="">Selecione</option>{classes.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label></div>{students.filter(s=>!attendanceClass||s.className===attendanceClass).map(s=>{const a=attendance.find(x=>x.studentId===s.id&&x.date===attendanceDate);return <div className="attendanceRow" key={s.id}><b>{s.name}</b><span>{a?.present===true?"Presente":a?.present===false?"Ausente":"Não lançado"}</span><div><button onClick={()=>markAttendance(s.id,true)}>Presente</button><button className="remove" onClick={()=>markAttendance(s.id,false)}>Ausente</button></div></div>})}</section>}
 {view==="calendar"&&<section className="card"><span className="badge">CALENDÁRIO ESCOLAR</span><h1>Calendário</h1>{isDirector&&<form onSubmit={addEvent}><div className="grid"><label>Evento<input value={eventForm.title} onChange={e=>setEventForm({...eventForm,title:e.target.value})} required/></label><label>Data<input type="date" value={eventForm.date} onChange={e=>setEventForm({...eventForm,date:e.target.value})} required/></label><label className="full">Descrição<textarea value={eventForm.description} onChange={e=>setEventForm({...eventForm,description:e.target.value})}/></label></div><button>Adicionar evento</button></form>}<div className="calendarList">{[...events].sort((a,b)=>a.date.localeCompare(b.date)).map(e=><div className="item" key={e.id}><b>{e.title}</b><span>{e.date}</span><p>{e.description}</p></div>)}{!events.length&&<p className="muted">Nenhum evento cadastrado.</p>}</div></section>}
 {view==="mail"&&<><section className="card"><span className="badge">E-MAIL</span><h1>Mensagens</h1><form onSubmit={addMail}><div className="grid"><label>Destinatário<select value={mailForm.toId} onChange={e=>setMailForm({...mailForm,toId:e.target.value})} required><option value="">Selecione</option>{users.filter(u=>u.id!==current.id&&u.active).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label><label>Assunto<input value={mailForm.subject} onChange={e=>setMailForm({...mailForm,subject:e.target.value})} required/></label><label className="full">Mensagem<textarea value={mailForm.body} onChange={e=>setMailForm({...mailForm,body:e.target.value})} required/></label></div><button>Enviar e-mail</button></form></section><section className="card"><h2>Caixa de entrada ({inbox.length})</h2>{inbox.map(m=><div className={m.read?"item":"item unread"} key={m.id} onClick={()=>markRead(m.id)}><b>{m.subject}</b><span>De: {users.find(u=>u.id===m.fromId)?.name||"Usuário"} · {new Date(m.date).toLocaleString("pt-BR")}</span><p>{m.body}</p></div>)}</section></>}
 {view==="profile"&&<section className="card"><span className="badge">PERFIL</span><h1>{current.name}</h1><div className="profileGrid"><div><span>Usuário</span><strong>@{current.username}</strong></div><div><span>E-mail</span><strong>{current.email||"Não informado"}</strong></div><div><span>Tipo</span><strong>{role}</strong></div><div><span>Turma</span><strong>{current.className||"Não se aplica"}</strong></div></div></section>}
 </main></div>
}